function outText = getDrawText(group, keyGroup)

    if strcmpi(group, 'R') && keyGroup == 1
       outText =  ['MAIN BLOCK\n\n' ...
        'You will hear words with background noise.\n\n' ... 
        'Listen to the word and decide if it is living \nor non-living.\n\n'... 
        'Press ''Z'' for living\n\n'...
        'Press ''M'' for non-living\n\n'...
        'The test will continue on its own after each answer.\n\n'...
        'Press the space bar when you are ready to start.']; 
    
    elseif strcmpi(group, 'R') && keyGroup == 2
       outText =  ['MAIN BLOCK\n\n' ...
        'You will hear words with background noise.\n\n' ... 
        'Listen to the word and decide if it is living \nor non-living.\n\n'... 
        'Press ''Z'' for non-living\n\n'...
        'Press ''M'' for living\n\n'...
        'The test will continue on its own after each answer.\n\n'...
        'Press the space bar \nwhen you are ready to start.']; 
    
    elseif strcmpi(group, 'D') && keyGroup == 1
        outText = ['MAIN BLOCK\n\n' ...
        'You will hear words with background noise.\n\n' ... 
        'Listen to the word and decide if it is high pitch.\n\n'... 
        'Press ''Z'' for low pitch\n'...
        'Press ''M'' for high pitch\n\n'...
        'The test will continue on its own after each answer.\n\n'...
        'Press the space bar when you are ready to start.'];
    
    elseif strcmpi(group, 'D') && keyGroup == 2
        outText = ['MAIN BLOCK\n\n' ...
        'You will hear words with background noise.\n\n' ... 
        'Listen to the word and decide if it is high pitch.\n\n'... 
        'Press ''Z'' for high pitch\n'...
        'Press ''M'' for low pitch\n\n'...
        'The test will continue on its own after each answer.\n\n'...
        'Press the space bar when you are ready to start.'];
    
    else
        error('Could not determine group and/or keyGroup')
    end
end